<?php
/**
 * @file
 * The main module file.
 *
 * Contains menu, permission, init, and page alter hook implementations.
 */


/**
 * Implements of hook_menu().
 */
function chartbeat_menu() {
  $items['admin/config/system/chartbeat'] = array(
    'title' => 'Chartbeat',
    'description' => 'Change the setting configuration when using Chartbeat.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chartbeat_admin_settings'),
    'access arguments' => array('administer chartbeat settings'),
    'file' => 'chartbeat.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function chartbeat_permission() {
  return array(
    'administer chartbeat settings' => array(
      'title' => t('Administer Chartbeat settings'),
    ),
  );
}

/**
 * Implementation of hook_init().
 */
function chartbeat_init() {
  $uid = variable_get('chartbeat_uid', '');
  if (is_numeric($uid)) {
    // Add the header script to start the timer.
    drupal_add_html_head(array(
      '#tag' => 'script',
      '#attributes' => array('type' => 'text/javascript'),
      '#value' => 'var _sf_startpt=(new Date()).getTime();',
    ), 'chartbeat');
    // Inject the Chartbeat settings.
    drupal_add_js(array('chartbeat' => array(
      'uid' => (int)$uid,
      'domain' => variable_get('chartbeat_domain', ''),
    )), 'setting');
  }
}

/**
 * Implements hook_page_alter().
 */
function chartbeat_page_alter(&$page) {
  $uid = variable_get('chartbeat_uid', '');
  if (!empty($uid)) {
    // Make sure we're outputting a user ID instead of a user name.
    if (!is_numeric($uid)) {
      drupal_set_message(t('Your <em>Chartbeat User ID</em> must be a number. You can locate it within step two of adding a new website to track at <a href="@chartbeat">Chartbeat</a>.', array('@chartbeat' => 'http://chartbeat.com')), 'warning', FALSE);
      return;
    }
    $output = <<<EOT
<script type="text/javascript">
  var _sf_async_config=Drupal.settings.chartbeat;
  (function(){
    function loadChartbeat() {
      window._sf_endpt=(new Date()).getTime();
      var e = document.createElement('script');
      e.setAttribute('language', 'javascript');
      e.setAttribute('type', 'text/javascript');
      e.setAttribute('src',
         (("https:" == document.location.protocol) ? "https://s3.amazonaws.com/" : "http://") +
         "static.chartbeat.com/js/chartbeat.js");
      document.body.appendChild(e);
    }
    var oldonload = window.onload;
    window.onload = (typeof window.onload != 'function') ?
       loadChartbeat : function() { oldonload(); loadChartbeat(); };
  })();
</script>
EOT;
    $page['page_bottom']['chartbeat'] = array('#markup' => $output);
  }
}
