<?php

/**
 * Implementation of hook_menu().
 */
function chartbeat_menu() {
  $items['admin/settings/chartbeat'] = array(
    'title' => 'Chartbeat',
    'description' => 'Change the setting configuration when using Chartbeat.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('chartbeat_admin_settings'),
    'access arguments' => array('administer chartbeat settings'),
    'file' => 'chartbeat.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function chartbeat_perm() {
  return array(
    'administer chartbeat settings',
  );
}

/**
 * Implementation of hook_init().
 */
function chartbeat_init() {
  $uid = variable_get('chartbeat_uid', '');
  $canonical = variable_get('chartbeat_use_canonical', '0');
  $canonical = !empty($canonical) ? TRUE : FALSE;

  $cookies = variable_get('chartbeat_cookies', '0');
  $cookies = !empty($cookies) ? FALSE : TRUE;

  if (is_numeric($uid)) {
    drupal_set_html_head('<script type="text/javascript">var _sf_startpt=(new Date()).getTime()</script>');
    drupal_add_js(array('chartbeat' => array(
      'uid' => (int)$uid,
      'domain' => variable_get('chartbeat_domain', ''),
      'useCanonical' => $canonical,
      'noCookies' => $cookies,
    )), 'setting');
  }
}

function chartbeat_theme_registry_alter(&$theme_registry) {
  $theme_registry['node_admin_nodes']['file'] = 'chartbeat.theme.inc';
  $theme_registry['node_admin_nodes']['theme path'] = drupal_get_path('module', 'chartbeat');
  $theme_registry['node_admin_nodes']['function'] = 'theme_chartbeat_node_admin_nodes';
  $theme_registry['node_admin_nodes']['include files'] = array("./" . drupal_get_path('module', 'chartbeat') . "/chartbeat.theme.inc");
  $theme_registry['node_admin_nodes']['theme paths'] = array(drupal_get_path('module', 'chartbeat'));
}

/**
 * Implementation of hook_footer().
 */
function chartbeat_footer() {
  $uid = variable_get('chartbeat_uid', '');
  if (is_numeric($uid)) {
    $output = <<<EOT
<script type="text/javascript">
  var _sf_async_config=Drupal.settings.chartbeat;
  (function(){
    function loadChartbeat() {
      window._sf_endpt=(new Date()).getTime();
      var e = document.createElement('script');
      e.setAttribute('language', 'javascript');
      e.setAttribute('type', 'text/javascript');
      e.setAttribute('src',
         (("https:" == document.location.protocol) ? "https://s3.amazonaws.com/" : "http://") +
         "static.chartbeat.com/js/chartbeat.js");
      document.body.appendChild(e);
    }
    var oldonload = window.onload;
    window.onload = (typeof window.onload != 'function') ?
       loadChartbeat : function() { oldonload(); loadChartbeat(); };
  })();
</script>
EOT;
    return $output;
  }
}
